name: workflow-1

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: welcome messaage
          run: echo "welcome messaage"
        - name: list files
          run: ls 
        - name: read files
          run: cat README.md