name: multi-job-workflow

on:  push

jobs:
    create-file:
        runs-on: ubuntu-latest
        steps:
            - name: create a file
              run: echo "sathish" > file.txt
            - name: upload the file
              uses: actions/upload-artifact@v4
              with:
                name: file
                path: file.txt
    
    read-file:
        needs: create-file
        runs-on: ubuntu-latest
        steps:
            - name: read a file
              run: cat file.txt 
   